name: Caching and Artifacts
on: workflow_dispatch

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-npm-cache-
          

      - name: Display Cache output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'
      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-coverage
          path: coverage
          retention-days: 1 #jak długo artefakt bedzie dostępny. Domyslnie 90 dni

      - name: Download code coverage
        uses: actions/download-artifact@v3
        if: always()
        with:
          name: code-coverage
          path: code-coverage-report

      - name: Display directory content
      - run: ls -a
      - run: ls -a
        working-directory: code-coverage-report
        if: always()


      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', {
              headers: {
                Accept: 'text/plain'
              }
            });
            console.log(res.data);