name: stale issues

on:
  schedule:
    - cron: "* * * * *" # Minutes / Hours / Day of the month / Month / Days of the week
                        #https://crontab.guru/ tu ładnie widać jak to działa
    - cron: "0 15 * * *" # 3pm every day
    - cron: "0/5 * * * *" # Every 5 minutes

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This is some msg"
          bays-before-stale: 1
          days-before-close: 5
