name: Vars and Secrets

on: [push]

jobs:
  decrypt-file:
    runs-on: ${{vars.JOBS_RUNNER}}
    steps:
      - uses actions/checkout@v3
      - name: Decrypt file
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="${GPG_PASSPHRASE}" --output $HOME/secrets/secret.json secret.json.gpg
      - name: View Encrypted File Content (NEVER DO THIS!)
        run: cat $HOME/secrets/secret.json
  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: 'prod'
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: $${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: $${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "BOOLEAN_SECRET is true"
      - name: Log Vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"