name: Working Dirs & Shells
on: [push]
defaults:
    run:
        shell: bash

jobs:
  display-wd-info-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Display workind directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: change working directory
        working-directory: /home/runner
        run: pwd


  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display workind directory & List Files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: run python shell
        shell: python
        run: |
          import platform
          print(platform.system())
